---
# Copyright 2014-2016 Rackspace Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags:
    - always

- include: install_dependencies.yml
  when:
    - ops_pip_dependencies is defined
    - ( inventory_hostname in groups[ 'neutron_agents_container' ] or inventory_hostname in groups[ 'shared-infra_hosts' ] or inventory_hostname in groups[ 'utility_container' ] )
  tags:
    - ops_dependencies

- include: rpc_release.yml
  tags:
    - rpc_release

- include: host_kernel_modules.yml
  when: >
    inventory_hostname in groups['hosts']
  tags:
    - host_kernel_tuning

- include: host_kernel_tuning.yml
  when: >
    inventory_hostname in groups['hosts']
  tags:
    - host_kernel_tuning

- include: disable_unattended_upgrades.yml
  tags:
    - ubuntu_apt_configuration

- include: configure_unattended_upgrades.yml
  tags:
    - ubuntu_apt_configuration

- include: support_preinstall.yml
  tags:
    - support_packages

- include: deploy_pccommon.yml
  when:
    - inventory_hostname in groups[ 'neutron_agents_container' ] or inventory_hostname in groups[ 'shared-infra_hosts' ] or inventory_hostname in groups[ 'utility_container' ]
  tags:
    - ops_pccommon
    - support_packages

- include: aacraid_tools.yml
  when:
    - install_aacraid | default(false)
    - inventory_hostname in groups[ 'swift_obj' ]
  tags:
    - ops_aacraid_conf
    - support_packages

- include: bashrc.yml
  tags:
    - bash_configuration

- include: bash_histformat.yml
  tags:
    - bash_configuration

- include: bash_autocompletion.yml
  tags:
    - bash_configuration

- include: motd.yml
  tags:
    - login_configuration

- include: spice_console.yml
  when: >
    inventory_hostname in groups['nova_console'] and nova_console_type == 'spice'
  tags:
    - nova_spice_console

- include: support_key_pair.yml
  when: >
    groups['nova_api_os_compute']|length > 0 and inventory_hostname == groups['utility'][0]
  tags:
    - support_nova_configuration

- include: support_sec_group.yml
  when: >
    groups['neutron_server']|length > 0 and inventory_hostname == groups['utility'][0]
  tags:
    - support_nova_configuration

- include: distribute_auth_key.yml
  when: >
    groups['nova_api_os_compute']|length > 0 and inventory_hostname == groups['utility'][0]
  tags:
    - support_nova_configuration

- include: retrieve_auth_key.yml
  when: >
    groups['nova_api_os_compute']|length > 0 and inventory_hostname != groups['utility'][0] and (inventory_hostname in groups['utility'] or inventory_hostname in groups['neutron_all'])
  tags:
    - support_nova_configuration

- include: support_magnum.yml
  when: >
    groups['magnum_all']|length > 0 and inventory_hostname == groups['utility'][0]
  tags:
    - support_packages

- include: holland_preinstall.yml
  when: >
    inventory_hostname in groups['galera']
  tags:
    - galera_holland_configuration

- include: holland_db_setup.yml
  when: >
    inventory_hostname == groups['galera'][0]
  tags:
    - galera_holland_configuration

- include: holland_config.yml
  when: >
    inventory_hostname in groups['galera']
  tags:
    - galera_holland_configuration

- include: holland_create_backupset.yml
  when: >
    inventory_hostname in groups['galera']
  tags:
    - galera_holland_configuration

- include: neutron_debug.yml
  when: >
    inventory_hostname in groups['neutron_agent']
  tags:
    - support_packages

- include: create_default_nova_flavors.yml
  when:  inventory_hostname == groups['utility'][0]
  tags:
    - support_nova_configuration

- include: sos.yml
  when:
    - inventory_hostname in groups['hosts']
  tags:
    - support_packages

- include: hp_firmware_updater.yml
  when:
    - inventory_hostname in groups['hosts']
    - ansible_system_vendor == "HP"
    - ops_update_hp_firmware | bool == true
  tags:
    - hp_firmware_updater
