---
# Copyright 2017-Present, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- import_playbook: "common-playbooks/register-openstack-release.yml"

- import_playbook: "common-playbooks/install-dependencies.yml"
  vars:
    host_group: "shared-infra_hosts"

- name: Create RPC support key
  hosts: shared-infra_hosts[0]
  gather_facts: "{{ gather_facts | default(true) }}"
  tasks:
    - name: Check for key file
      stat:
        path: /root/.ssh/rpc_support
      changed_when: false
      failed_when: false
      register: support_key_check

    - name: Create support SSH key
      command: |
        ssh-keygen -f "/root/.ssh/rpc_support" -t rsa -q -N ""
      register: support_key_create
      changed_when: support_key_create.rc == 0
      failed_when: support_key_create.rc >= 1
      when: not support_key_check.stat.exists |bool

    - name: Get contents of support SSH key
      slurp:
        src: "/root/.ssh/rpc_support"
      register: support_key
      when: support_key_check.stat.exists |bool or support_key_create is changed

    - name: Get contents of support SSH pub key
      slurp:
        src: "/root/.ssh/rpc_support.pub"
      register: support_pub_key
      when: support_key_check.stat.exists |bool or support_key_create is changed

    - name: Determine ssh-keygen hash option
      shell: |
        ssh-keygen --help 2>&1 | grep -q '\-E fingerprint_hash'
      register: ssh_keygen_has_hash_opt
      changed_when: ssh_keygen_has_hash_opt.rc == 0
      ignore_errors: yes
      failed_when: false

    - name: Get fingerprint of rpc_support SSH key (old method)
      shell: |
        ssh-keygen -lf /root/.ssh/rpc_support.pub |awk '/(RSA|DSA)/ {print $2}'
      register: support_key_fingerprint
      changed_when: support_key_fingerprint.rc == 0
      failed_when: false
      when:
        - support_key_check.stat.exists |bool or support_key_create is changed
        - ssh_keygen_has_hash_opt is undefined

    - name: Get fingerprint of rpc_support SSH key
      shell: |
        ssh-keygen -l -E md5 -f /root/.ssh/rpc_support.pub |awk -F'MD5:' '/(RSA|DSA)/ {print substr($2,1,48)}'
      register: support_key_fingerprint
      changed_when: support_key_fingerprint.rc == 0
      failed_when: false
      when:
        - support_key_check.stat.exists |bool or support_key_create is changed
        - ssh_keygen_has_hash_opt is defined
        - ssh_keygen_has_hash_opt is success

    - name: SSH Key fingerprint on disk
      debug: msg="{{ support_key_fingerprint.stdout }}"

    - name: Check for support keypair in nova
      shell: |
        . /root/openrc
        {{ ops_venv }}/bin/nova keypair-list | grep rpc_support
      register: nova_support_key
      changed_when: false
      failed_when: false

    - name: nova SSH Key fingerprint
      debug: msg="{{ nova_support_key.stdout }}"

    - name: Delete support keypair in nova
      shell: |
        . /root/openrc
        {{ ops_venv }}/bin/nova keypair-delete rpc_support
      register: nova_support_key_delete
      changed_when: nova_support_key_delete.rc == 0
      failed_when: false
      retries: 2
      delay: 10
      when: nova_support_key.rc == 0 and support_key_fingerprint.stdout not in nova_support_key.stdout

    - name: Add support key to nova
      shell: |
        . /root/openrc
        {{ ops_venv }}/bin/nova keypair-add --pub-key /root/.ssh/rpc_support.pub rpc_support
      retries: 2
      delay: 10
      when: nova_support_key_delete is changed or nova_support_key.rc == 1
  vars_files:
    - "vars/main.yml"

- name: Get local RPC support pubkey hash
  hosts: shared-infra_hosts:utility_container:neutron_agents_container
  gather_facts: "false"
  tasks:
    - name: Retreive local support SSH key stats
      stat:
        path: /root/.ssh/rpc_support
      changed_when: false
      failed_when: false
      register: local_support_key_check

- name: Distribute RPC support key
  hosts: shared-infra_hosts[1:999]:utility_container:neutron_agents_container:openstack_control_plane
  gather_facts: "false"
  tasks:
    - name: Distribute support SSH key for cluster operations
      copy:
        dest: "{{ item.dest }}"
        content: "{{ item.content }}"
        owner: "root"
        group: "root"
        mode: "0600"
      with_items:
        - dest: "/root/.ssh/rpc_support"
          content: "{{ hostvars[groups['shared-infra_hosts'][0]]['support_key'].content | b64decode }}"
        - dest: "/root/.ssh/rpc_support.pub"
          content: "{{ hostvars[groups['shared-infra_hosts'][0]]['support_pub_key'].content | b64decode }}"
      when:
        - ( hostvars[groups['shared-infra_hosts'][0]]['support_pub_key'].content |default('') |length > 64 or
            hostvars[groups['openstack_control_plane'][0]]['support_pub_key'].content |default('') |length > 64 )
        - ( hostvars[groups['shared-infra_hosts'][0]]['support_key'].content |b64decode |hash('sha1') != local_support_key_check.stat.checksum |default('') or
            hostvars[groups['openstack_control_plane'][0]]['support_key'].content |b64decode |hash('sha1') != local_support_key_check.stat.checksum |default('') )
  vars_files:
    - "vars/main.yml"
