---
# 2017-Present, Bjoern Teipel <bjoern.teipel@rackspace.com>
#
# Play to tear down Swift data nodes
#
# WARNING: This playbook will stop the swift services on the swift_obj server group and unmount/reformat/remount the XFS disks
#          mounted under /srv/node. If there is no disk mounted, the play will not execute any tasks.
#
#                                 !!!!! DATA WILL BE DELETED WHEN RUNNING THIS PLAY !!!!!
#
# Overrides:
# - xfs_inode_size defaults to 1024 and is used for the -i parameter with mkfs.xfs
# - xfs_mount_options default to rw,noatime,nodiratime,nobarrier,logbufs=8,noquota
# - xfs_format_options defaults to ""
# - exclude_drive_labels defaults to ""
# - exclude_drive_labels_format_option to ""
#
# Run it:
# openstack-ansible swift-datacrusher.yml
#
# Options can be overridden with passing these arguments to openstack-ansible:
# openstack-ansible swift-datacrusher.yml -e xfs_inode_size=256 -e xfs_format_options='-linternal' -e exclude_drive_labels="disk1,disk2" -e exclude_drive_labels_format_option="disk3,disk4"

- hosts: swift_obj
  vars_prompt:
    - name: destroy_swift_data
      prompt: "Do you really want to erase the swift cluster?"
      default: False
  pre_tasks:
    - name: Register mountpoints
      #For active XFS mounts: awk '/\/srv\/node/ { split($2,i,"/"); print $1 "," i[4] }' /proc/mounts
      #For any XFS mount: blkid -n xfs /dev/sd* |awk '/LABEL=\"disk/ { split($0,blkid,"\n"); for (n in blkid) { if (substr(blkid[n],0,5) == "/dev/") { device=$1; pos=match(blkid[n],"LABEL="); if (pos > 0) { str=device","substr(blkid[n],pos+7,6); gsub(":|\"","",str); print str } } } }'
      shell: |
        blkid -n xfs /dev/sd* |awk '/LABEL=\"disk/ { split($0,blkid,"\n"); for (n in blkid) { if (substr(blkid[n],0,5) == "/dev/") { device=$1; pos=match(blkid[n],"LABEL="); if (pos > 0) { str=device","substr(blkid[n],pos+7,6); gsub(":|\"","",str); print str } } } }'
      register: swift_drives
      changed_when: false
      tags:
        - "always"
  tasks:
    - name: Stop Swift Services
      service:
        name: "{{ item }}"
        state: stopped
      with_items:
        - "swift-object-server"
        - "swift-object-replicator"
        - "swift-container-reconciler"
        - "swift-object-expirer"
        - "swift-object-updater"
        - "swift-object-auditor"
        - "swift-container-server"
        - "swift-container-replicator"
        - "swift-container-updater"
        - "swift-container-auditor"
        - "swift-account-server"
        - "swift-account-replicator"
        - "swift-account-reaper"
        - "swift-account-auditor"
        - "swift-container-sync"
        - "rsync"
      when: destroy_swift_data |bool
      tags:
        - "service-stop"
        - "service-restart"
        - "remount"

    - name: Unmount Swift disks
      command: umount -f /srv/node/{{ item.split(',')[1] }}
      with_items: "{{ swift_drives.stdout_lines }}"
      when:
        - "{{ swift_drives.stdout_lines | length > 0 }}"
        - "{{ item.split(',')[1] not in ( exclude_drive_labels | default ({}) ) }}"
        - destroy_swift_data |bool
      tags:
        - "remount"
        - "umount"

    - name: Format Swift disk
      command: mkfs.xfs -L {{ item.split(',')[1] }} -f -i size={{ xfs_inode_size |default('1024') | int }} {{ xfs_format_options |default('') }} {{ item.split(',')[0] }}
      with_items: "{{ swift_drives.stdout_lines }}"
      register: swift_mkfs
      changed_when: '"Writing inode tables: done" in swift_mkfs.stdout'
      when:
        - "{{ swift_drives.stdout_lines | length > 0 }}"
        - "{{ item.split(',')[1] not in ( exclude_drive_labels | default ({}) ) }}"
        - "{{ item.split(',')[1] not in ( exclude_drive_labels_format_option | default ({}) ) }}"
        - destroy_swift_data |bool
      tags: format-xfs

    - name: Format Swift disk excluded options
      command: mkfs.xfs -L {{ item.split(',')[1] }} -f -i size={{ xfs_inode_size |default('1024') | int }} {{ item.split(',')[0] }}
      with_items: "{{ swift_drives.stdout_lines }}"
      register: swift_mkfs_exclude
      changed_when: '"Writing inode tables: done" in swift_mkfs_exclude.stdout'
      when:
        - "{{ swift_drives.stdout_lines | length > 0 }}"
        - "{{ item.split(',')[1] not in ( exclude_drive_labels | default ({}) ) }}"
        - "{{ item.split(',')[1] in ( exclude_drive_labels_format_option | default ({}) ) }}"
        - destroy_swift_data |bool
      tags: format-xfs

    - name: Mount Swift disks
      mount:
        name: "/srv/node/{{ item.split(',')[1] }}"
        src: "LABEL={{ item.split(',')[1] }}"
        fstype: xfs
        opts: "{{ xfs_mount_options |default('rw,noatime,nodiratime,nobarrier,logbufs=8,noquota') }}"
        state: mounted
      with_items: "{{ swift_drives.stdout_lines }}"
      when:
        - "{{ swift_drives.stdout_lines | length > 0 }}"
        - "{{ item.split(',')[1] not in ( exclude_drive_labels | default ({}) ) }}"
        - destroy_swift_data |bool
      tags:
        - "remount"
        - "mount"

    - name: Fix Swift Mountpoint permissions
      file:
        name: "/srv/node/{{ item.split(',')[1] }}"
        mode: "0755"
        owner: "swift"
        group: "swift"
      with_items: "{{ swift_drives.stdout_lines }}"
      when:
        - "{{ swift_drives.stdout_lines | length > 0 }}"
        - "{{ item.split(',')[1] not in ( exclude_drive_labels | default ({}) ) }}"
        - destroy_swift_data |bool
      tags: fix-permissions

    - name: Start Swift Services
      service:
        name: "{{ item }}"
        state: started
      with_items:
        - "swift-object-server"
        - "swift-object-replicator"
        - "swift-container-reconciler"
        - "swift-object-expirer"
        - "swift-object-updater"
        - "swift-object-auditor"
        - "swift-container-server"
        - "swift-container-replicator"
        - "swift-container-updater"
        - "swift-container-auditor"
        - "swift-account-server"
        - "swift-account-replicator"
        - "swift-account-reaper"
        - "swift-account-auditor"
        - "swift-container-sync"
        - "rsync"
      when: destroy_swift_data |bool
      tags:
        - "service-start"
        - "service-restart"
        - "remount"
